---
- name: Undeploy LaravelIO Service
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: laravelio-service
        namespace: "{{ namespace }}"
        labels:
          app: laravelio

- name: Undeploy HPA LaravelIO
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: autoscaling/v1
      kind: HorizontalPodAutoscaler
      metadata:
        name: laravelio-hpa
        namespace: "{{ namespace }}"

- name: Undeploy LaravelIO Deployment
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: laravelio-deployment
        namespace: "{{ namespace }}"
        labels:
          app: laravelio

- name: Delete MySQL Deployment
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Deployment
      metadata:
        name: mysql-deployment
        namespace: "{{ namespace }}"
        labels:
          app: mysql
          tier: database

- name: Delete MySQL Service
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: mysql
        namespace: "{{ namespace }}"
        labels:
          app: mysql

- name: Delete MySQL PersistentVolumeClaim
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: mysql-pv-claim
        namespace: "{{ namespace }}"

- name: Delete MySQL StorageClass
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: "{{ storagename }}"
